### Integrations - Alexa Media Player ###

# Description: The manual alarm control panel platform enables you to create an alarm system in Home Assistant.
#
# Requires: 
#  - Manual Alarm control panel
#    https://www.home-assistant.io/integrations/manual
#

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_disarm_code
    code_arm_required: false # Don't need code to arm.
    disarm_after_trigger: false # Leave alarm armed after triggering.
    arming_time: 30 # Time to leave the house after arming.
    delay_time: 60 # Time to turn off after entering the house.
    trigger_time: 120 # How long the alarm goes off for.
    disarmed:
      trigger_time: 0 # Can't be triggered when disarmed.
    armed_home:
      arming_time: 0 # Arm instantly when at home.
      delay_time: 0 # Trigger instantly when at home.