### Integrations - Core ###

# Description: manage core configurations
#
# Requires:
#  - Recorder 
#    https://www.home-assistant.io/integrations/recorder/
#

recorder:
  auto_purge: true      
  purge_keep_days: 15   # The number of history days to keep in recorder database
  exclude: 
    domains: 
      - automation
      - camera
      #- device_tracker
      #- group
      - input_datetime
      #- light
      #- person
      - sun
      - script
      - zone
    entities: 
      - sun.sun
      - sensor.last_boot
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.hacs