#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
#- 

- platform: template
  sensors:
    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state('binary_sensor.activity_in_living_room', 'on')
            or is_state('binary_sensor.activity_in_hall', 'on') }}

    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state('binary_sensor.motion_detected', 'on') }}
      delay_off: '01:00:00'

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state('binary_sensor.motion_detected_in_last_hour', 'on')
            or is_state('group.person_family', 'home') }}

    activity_in_living_room:
      friendly_name: Activity in the living room
      value_template: >
        {{  is_state('binary_sensor.motion_living_occupancy', 'on')
            or is_state('media_player.tv', 'on') }}
      delay_off: '00:20:00'

    activity_in_hall:
      friendly_name: Activity in the hall
      value_template: >
        {{ is_state('binary_sensor.motion_hall_occupancy', 'on')
            or is_state('binary_sensor.doorcontact_hall_contact', 'on') }}
      delay_off: '00:01:00'

    activity_outside_front_door:
      friendly_name: Activity outside front door
      value_template: >
        {{ is_state('binary_sensor.motion_sensor_outside_front_door_occupancy', 'on')
            or is_state('binary_sensor.doorcontact_hall_contact', 'on') }}
      delay_off: '00:01:00'

    activity_outside_house:
      friendly_name: Activity outside house
      value_template: >
        {{ is_state('binary_sensor.activity_outside_garage', 'on')
          or is_state('binary_sensor.activity_outside_front_door', 'on') }}
      delay_off: '00:01:00'

    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ is_state('binary_sensor.lave_linge_hublot', 'on') }}
      delay_off: '00:05:00'
      icon_template: >
        {% if is_state('binary_sensor.lave_linge_hublot', 'on') %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set automatic_lights_on = is_state('light.automatic_lights', 'on') %}
        {% set bedroom_lights_on = is_state('light.bedroom_lights', 'on') %}
        {% set living_room_lights_on = is_state('light.living_room_lights', 'on') %}
        {{ automatic_lights_on or bedroom_lights_on or living_room_lights_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state('binary_sensor.any_light_on', 'on') %}
        {% set tv_on = not is_state('media_player.tv', 'off') %}
        {{ light_on or tv_on }}

    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state('group.person_family', 'home') }}
        