#- 
#                            
#   ___ _____   _____ _ __ ___ 
#  / __/ _ \ \ / / _ \ '__/ __|
# | (_| (_) \ V /  __/ |  \__ \
#  \___\___/ \_/ \___|_|  |___/
#                              
#
#-

- platform: template
  covers:
    shutter_study:
      device_class: shutter
      unique_id: cover_study
      friendly_name: 'Volet Bureau'
      optimistic: true
      #value_template: '{{is_state('sensor.cover_study', 'open')}}'
      open_cover:
        service: rest_command.airsend_command_setstate
        data:
          id: !secret airsend_shutter_study_channel_id
          source: !secret airsend_shutter_study_channel_source
          command: 'UP'
      close_cover:
        service: rest_command.airsend_command_setstate
        data:
          id: !secret airsend_shutter_study_channel_id
          source: !secret airsend_shutter_study_channel_source
          command: 'DOWN'
      stop_cover:
        service: rest_command.airsend_command_setstate
        data:
          id: !secret airsend_shutter_study_channel_id
          source: !secret airsend_shutter_study_channel_source
          command: 'STOP'
      #icon_template: >-
        #{% if is_state('sensor.airsend_bureau', 'open') %}
        #mdi:window-shutter-open
        #{% else %}
        #mdi:window-shutter
        #{% endif %}

    shutter_living:
        device_class: shutter
        unique_id: cover_living
        friendly_name: 'Volets Salon'
        optimistic: true
        open_cover:
          service: rest_command.airsend_command_setstate
          data:
            id: !secret airsend_shutter_living_channel_id
            source: !secret airsend_shutter_living_channel_source
            command: 'UP'
        close_cover:
          service: rest_command.airsend_command_setstate
          data:
            id: !secret airsend_shutter_living_channel_id
            source: !secret airsend_shutter_living_channel_source
            command: 'DOWN'
        stop_cover:
          service: rest_command.airsend_command_setstate
          data:
            id: !secret airsend_shutter_living_channel_id
            source: !secret airsend_shutter_living_channel_source
            command: 'STOP'

    shutter_bedrooms:
        device_class: shutter
        unique_id: cover_bedrooms
        friendly_name: 'Volets Chambres'
        optimistic: true
        open_cover:
        close_cover:
        stop_cover: