#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#-

- platform: template
  lights:
    table_lamp_living:
      friendly_name: 'Lampe Salle à manger'
      turn_on:
        service: rest_command.airsend_command_setstate
        data:
            id: !secret airsend_dio_plug_1_channel_id
            source: !secret airsend_dio_plug_1_channel_source
            command: 'ON'
      turn_off:
        service: rest_command.airsend_command_setstate
        data:
            id: !secret airsend_dio_plug_1_channel_id
            source: !secret airsend_dio_plug_1_channel_source
            command: 'OFF'

    floor_lamp_living:
      friendly_name: 'Lampadaire Salle à manger'
      turn_on:
        service: rest_command.airsend_command_setstate
        data:
            id: !secret airsend_dio_plug_2_channel_id
            source: !secret airsend_dio_plug_2_channel_source
            command: 'ON'
      turn_off:
        service: rest_command.airsend_command_setstate
        data:
            id: !secret airsend_dio_plug_2_channel_id
            source: !secret airsend_dio_plug_2_channel_source
            command: 'OFF'

- platform: group
  name: Living room lights
  entities:
    - light.table_lamp_living
    - light.floor_lamp_living