#-
#              _   _  __
#  _ __   ___ | |_(_)/ _|_   _
# | '_ \ / _ \| __| | |_| | | |
# | | | | (_) | |_| |  _| |_| |
# |_| |_|\___/ \__|_|_|  \__, |
#                        |___/
#
#-

- platform: group
  name: admin
  services:
    - service: mobile_app_iphone_12_tom

- platform: group
  name: all
  services:
    - service: mobile_app_iphone_12_tom
    #- service: tv
    #- service: chrome
