# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  #base_url: https://koalant.ddns.net

# Devices
binary_sensor: !include includes/binary_sensors.yaml
cover: !include includes/covers.yaml
#sensor: !include sensors.yaml
group: !include includes/groups.yaml
homekit: !include includes/homekit.yaml
notify: !include includes/notify.yaml
light: !include includes/lights.yaml
person: !include includes/persons.yaml
zone: !include includes/zones.yaml

# Managed with packages
automation: !include automations.yaml
#script: !include_dir_merge_named scripts
#script: !include scripts.yaml
scene: !include scenes.yaml
#secrets: !include secrets.yaml