
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
# This is a dummy file for using when testing the configuration
# The file was be renamed as 'secrets.yaml'

some_password: welcome

latitude_home: 45.750000
longitude_home: 4.850000

alarm_disarm_code: 1234

# Airsend duo
airsend_ip: 192.168.1.255
airsend_ws_url: http://127.0.0.1:9090/airsend/transfer
airsend_ws_http_headers_auth: Bearer sp://abc123@192.168.1.255?gw=0

## Devices
airsend_dio_plug_1_channel_id: 124
airsend_dio_plug_1_channel_source: 102030
airsend_dio_plug_2_channel_id: 456
airsend_dio_plug_2_channel_source: 204060

airsend_shutter_study_channel_id: 789
airsend_shutter_study_channel_source: 103050
airsend_shutter_living_channel_id: 468
airsend_shutter_living_channel_source: 406080
